// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssociateOpen() {
  return window['go']['main']['App']['AssociateOpen']();
}

export function ExportHtmlEvent() {
  return window['go']['main']['App']['ExportHtmlEvent']();
}

export function ExportPdfEvent() {
  return window['go']['main']['App']['ExportPdfEvent']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function SaveAsFileEvent() {
  return window['go']['main']['App']['SaveAsFileEvent']();
}

export function SaveFileEvent() {
  return window['go']['main']['App']['SaveFileEvent']();
}
