// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {file} from '../models';

export function AssociateOpen():Promise<file.File>;

export function ExportHtmlEvent():Promise<void>;

export function ExportPdfEvent():Promise<void>;

export function OpenFile():Promise<void>;

export function SaveAsFileEvent():Promise<void>;

export function SaveFileEvent():Promise<void>;
