# This is a basic workflow to help you get started with Actions

name: wailsBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - "v*"
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linux-amd64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "linux-amd64"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          repository: "langbiantianya/cherry-markdown-webview"
          submodules: recursive
      - uses: langbiantianya/cherry-markdown-webview@main
        with:
          build-name: cherryMarkdown
          build-platform: linux/amd64
          wails-build-webview2: "embed"
          wails-version: v2.9.2
          go-version: ^1.21
          sign: "false"

  macos:
    runs-on: macos-latest
    env:
      JOB_NAME: "darwin-universal"
    steps:
      # Checkout code
      - uses: actions/checkout@v4
        with:
          repository: "langbiantianya/cherry-markdown-webview"
          submodules: recursive
      - uses: langbiantianya/cherry-markdown-webview@main
        with:
          build-name: cherry-markdown-webview
          build-platform: darwin/universal
          wails-build-webview2: "embed"
          wails-version: "v2.9.2"
          go-version: ^1.21
          sign: "false"
  # sign-macos-apple-password: ${{ secrets.APPLE_PASSWORD }}
  # sign-macos-app-id: "Developer ID Application: Lethean LTD (W2DNA5L5DY)"
  # sign-macos-app-cert: ${{ secrets.MAC_DEVELOPER_CERT }}
  # sign-macos-app-cert-password: ${{ secrets.MAC_DEVELOPER_PASS }}
  # sign-macos-installer-id: "Developer ID Installer: Lethean LTD (W2DNA5L5DY)"
  # sign-macos-installer-cert: ${{ secrets.MAC_DEVELOPER_INSTALL_CERT }}
  # sign-macos-installer-cert-password: ${{ secrets.MAC_DEVELOPER_INSTALL_PASS }}

  windows-amd64:
    runs-on: windows-2022
    env:
      JOB_NAME: "windows-amd64"
    steps:
      # Checkout code
      - uses: actions/checkout@v4
        with:
          repository: "langbiantianya/cherry-markdown-webview"
          submodules: recursive
      - uses: langbiantianya/cherry-markdown-webview@main
        with:
          build-name: cherryMarkdown.exe
          build-platform: windows/amd64
          wails-build-webview2: "embed"
          wails-version: v2.9.2
          go-version: ^1.21
          nsis: "true"

  windows-arm64:
    runs-on: windows-2022
    env:
      JOB_NAME: "windows-arm64"
    steps:
      # Checkout code
      - uses: actions/checkout@v4
        with:
          repository: "langbiantianya/cherry-markdown-webview"
          submodules: recursive
      - uses: langbiantianya/cherry-markdown-webview@main
        with:
          build-name: cherryMarkdown.exe
          build-platform: windows/arm64
          wails-build-webview2: "embed"
          wails-version: v2.9.2
          go-version: ^1.21
          nsis: "true"
