# This is a basic workflow to help you get started with Actions

name: wailsBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - "v*"
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            {
              name: linux,
              platform: linux/amd64,
              os: ubuntu-22.04,
              nsis: false,
              build-name: "cherryMarkdown"
            },
            {
              name: macos,
              platform: darwin/universal,
              os: macos-latest,
              nsis: false,
              build-name: "cherry-markdown-webview"
            },
            {
              name: windows,
              platform: windows/amd64,
              os: windows-2022,
              nsis: true,
              build-name: "cherryMarkdown.exe"
            },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build-obfuscate: true
          go-version: 1.24.4
          wails-build-webview2: "embed"
          sign: "false"
          nsis: ${{ matrix.build.nsis }}
