# This is a basic workflow to help you get started with Actions

name: wailsBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - "v*"
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  mac-and-linux:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: linux-amd64, platform: linux/amd64, os: ubuntu-22.04},
          {name: macos, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build-obfuscate: true
  windows-amd64:
    runs-on: windows-2022
    steps:
      # Checkout code
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: cherryMarkdown.exe
          build-platform: windows/amd64
          wails-build-webview2: "embed"
          nsis: "true"

  windows-arm64:
    runs-on: windows-2022
    steps:
      # Checkout code
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: cherryMarkdown.exe
          build-platform: windows/arm64
          wails-build-webview2: "embed"
          nsis: "true"
