// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AboutEvent() {
  return window['go']['main']['App']['AboutEvent']();
}

export function AssociateOpen() {
  return window['go']['main']['App']['AssociateOpen']();
}

export function ExportHtmlEvent() {
  return window['go']['main']['App']['ExportHtmlEvent']();
}

export function ExportPdfEvent() {
  return window['go']['main']['App']['ExportPdfEvent']();
}

export function GetActivatedTheme() {
  return window['go']['main']['App']['GetActivatedTheme']();
}

export function GetPicBed() {
  return window['go']['main']['App']['GetPicBed']();
}

export function GetSaved() {
  return window['go']['main']['App']['GetSaved']();
}

export function GetThemeList() {
  return window['go']['main']['App']['GetThemeList']();
}

export function GetWebServerPort() {
  return window['go']['main']['App']['GetWebServerPort']();
}

export function IssuesEvent() {
  return window['go']['main']['App']['IssuesEvent']();
}

export function LoadTheme(arg1) {
  return window['go']['main']['App']['LoadTheme'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenFileEvent() {
  return window['go']['main']['App']['OpenFileEvent']();
}

export function OptionsEvent() {
  return window['go']['main']['App']['OptionsEvent']();
}

export function PersonalizaEvent() {
  return window['go']['main']['App']['PersonalizaEvent']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function QuitEvent() {
  return window['go']['main']['App']['QuitEvent']();
}

export function ReadLocalFile(arg1) {
  return window['go']['main']['App']['ReadLocalFile'](arg1);
}

export function SaveAsFileEvent() {
  return window['go']['main']['App']['SaveAsFileEvent']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveFileEvent() {
  return window['go']['main']['App']['SaveFileEvent']();
}

export function SelectLocalFile(arg1) {
  return window['go']['main']['App']['SelectLocalFile'](arg1);
}

export function SetActivatedTheme(arg1) {
  return window['go']['main']['App']['SetActivatedTheme'](arg1);
}

export function SetBackground(arg1) {
  return window['go']['main']['App']['SetBackground'](arg1);
}

export function SetSaved(arg1) {
  return window['go']['main']['App']['SetSaved'](arg1);
}

export function UploadPicbed(arg1) {
  return window['go']['main']['App']['UploadPicbed'](arg1);
}

export function UpsertPicBed(arg1) {
  return window['go']['main']['App']['UpsertPicBed'](arg1);
}

export function UpsertThemeItem(arg1) {
  return window['go']['main']['App']['UpsertThemeItem'](arg1);
}
